### ISSUE TITLE
Gui changes

### ISSUE THREAD

**Issue by thb42** [tuiSSE/win-sshfs#12]
- Adding Text nex to the icons
- multiple lines, Servername in bold following lines in grey
- formated text output
- more space between the menu icons 
- name instead of nickname
- folder name is missing
- folder for virtual drive
- grey out save changes, if nothing is changed

**Comment by Tagun** [comment]
ich habe mal recherchiert wie man die multiple lines macht. Dabei ergab sich das es in einem TreeView Element nicht möglich ist, einen Text in mehreren Zeilen darzustellen. In einem ListView ist es allerdings über Environment.NewLine möglich, dort kann man aber keine Unterordner, sondern nur Gruppen erstellen.

**Comment by ThomDietrich** [comment]
Mit diesem Beispiel ist es mir möglich multiline Text einzufügen: http://msdn.microsoft.com/de-de/library/system.windows.forms.treeview.drawnode%28v=vs.110%29.aspx
Code:

```
node = myTreeView.Nodes.Add(String.Format("Task {0}" + Environment.NewLine + "Test", x));
```

Alternativ gibt es noch diese Möglichkeit:
http://objectlistview.sourceforge.net/cs/index.html
http://objectlistview.sourceforge.net/cs/recipes.html?highlight=treeview#how-do-i-use-a-treelistview
