### ISSUE TITLE
Mount all Funktioniert noch nicht

### ISSUE THREAD

**Issue by bjoe-phi** [tuiSSE/win-sshfs#30]
In der GUI sollte es möglich sein alle Folder eines Servers mit einem Klick zu mounten.
(Wollen wir das noch umsetzen oder streichen?)

**Comment by MSementsov** [comment]
Wenn es nicht als Pflicht markiert ist, würde ich vorschlagen es erstmal rauszunehmen und wenn wir Zeit haben am Ende es einzufügen. Im Moment gibt es noch einige wichtigere Aufgaben.

**Comment by bjoe-phi** [comment]
Steht im Pflichtenheft!
-> siehe M6 und dazugehörige Erklärung "Eintrag mounten", vorletzter Stichpunkt auf Seite 8

**Comment by MSementsov** [comment]
Habe es hinzugefügt.
