### ISSUE TITLE
Kontextmenu ist noch unvollständig

### ISSUE THREAD

**Issue by bjoe-phi** [tuiSSE/win-sshfs#35]
Siehe M6:

Server: "mounten", "unmounten", "löschen", "bearbeiten", "duplizieren", "neuen Ordnern hinzufügen"
Folder: "mounten", "unmounten", "löschen", "bearbeiten", "duplizieren", "Ordnern öffnen"

"mounten" ist bereits da, "unmounten" aber nicht. Entweder müssen beide da sein und jeweils ausgegraut sein, oder aber nur eins, welches seine Funktion ändert ...

**Comment by MSementsov** [comment]
Da aber nur Ordner gemountet werden und nicht Server, ist es in meinen Augen nicht sinnvoll diese Schaltflächen dort hinzuzufügen(auch wenn es in M6 steht), außer man fasst es mit dem anderen Issue zusammen und ändert diese Funktionen auf "Mount All" und "Unmount All".

**Comment by bjoe-phi** [comment]
Ja, aber man kann übers Kontextmenu noch nicht UNmounten!
Edit: Korrigiere, "unmount" existier bei Folder ja schon, aber bei Server noch nicht. Ja das hängt auch mit Issue #30 zusammen.

**Comment by bjoe-phi** [comment]
Bei Server fehlt noch das duplizieren...

**Comment by bjoe-phi** [comment]
Bei Server fehlt noch "Unmount all"
