### ISSUE TITLE
Startroutine der Software einrichten

### ISSUE THREAD

**Issue by Rokul** [tuiSSE/win-sshfs#45]
Autostart ins Backend verlagern,Backend zuerst starten gegebenfalls GUI und cmdline danach.
Loglevel

**Comment by thb42** [comment]
Um den Autostart sollte sich Windows kümmern, wenn der Registry-Eintrag erstellt wurde.
Im orgina wird Sshfs/Programm.cs aufgrufen, dort wird alles gestartet was benötigt wird.
Ich versuche z.Z. das Backend als Dienst zu starten, damit es kein Fesnter erhält, muss dafür aber noch mal mit BjöPhi reden.

**Comment by thb42** [comment]
Der Autostart eintrag in der Registry eintrag muss auf GUI\ConsoleApplication1.exe zeigen.

**Comment by bjoe-phi** [comment]
Starten ist geklärt, beenden des Backends muss noch hinzugefügt werden, siehe Issue #57
