### ISSUE TITLE
Neue treeView Hintergrundfarbe

### ISSUE THREAD

**Issue by MSementsov** [tuiSSE/win-sshfs#46]
Wenn der treeView nicht im Fokus ist, zeigt es die SelectedNode noch ausgegraut an. Allerdings ist dieses Grau so schwach, dass man es auf dem weißen hintergrund nicht sehen kann. Da ich bis jetzt auch keine Lösung gefunden hab(auch nach angemessener Googlezeit nicht) wie ich die Farbe von Grau auf [wasanderes] ändern kann, hab ich die Hintergrundfarbe erstmal geändert, damit man es erkennen kann.

Die Frage ist jetzt, kann man die Farbe so lassen, oder findet ihr die hässlich, wenn ja, dann stell ich es wieder auf weiß um, allerdings tritt dann das o.g. Problem wieder auf.

**Comment by bjoe-phi** [comment]
Workaround: Man könnte auch das Icon ändern, wenn man den Eintrag bearbeitet, zum Beispiel zu dem Stift. Dann weiß man auch immer welches Icon man gerade bearbeitet.

**Comment by chsc0817** [comment]
Hintergrund auf Wunsch wieder weiß
