### ISSUE TITLE
Bessere Integration des Virtual Drive

### ISSUE THREAD

**Issue by Tagun** [tuiSSE/win-sshfs#52]
M10 aus dem Pflichtenheft ist noch nicht erfüllt:
Im Bearbeitungsdialog von Ordnereinträgen wird der, für Virtual Drive eingestellte,
Laufwerksbuchstabe angezeigt und ein Ordnername für das Virtual Drive vorgeschlagen,
sodass der Nutzer die Funktion des Virtual Drive einfacher versteht.

**Comment by bjoe-phi** [comment]
GUI gibt jetzt einen Defaultwert an, bestehend aus Name des Laufwerks und dem Zusatz " directory"
