### ISSUE TITLE
Fehler mit Virtual Drive 

### ISSUE THREAD

**Issue by thb42** [tuiSSE/win-sshfs#56]
Wenn ich ein Verzeichnis im Virtual Drive Mounte kann ich nicht darauf zugreifen. Es kommt eine Fehlermeldenung, sinngemäß vergewissern sie sich, dass das Laufwerk angeschlossen ist oder das Netzwerklaufwerk verfügbar ist.

**Comment by bjoe-phi** [comment]
Kannst du den Fehler reproduzieren und nähere Inforamtionen liefer?
Bei mir funktioniert Virtual-Drive nämlich ohne Fehler.
Überprüfe bitte auch, welche Dokan-Library-Version bei dir installiert ist.

**Comment by thb42** [comment]
> .< Fehler gefunden, der Ordnername darf keine  "/" enthalten. Sollte man vllt als Bedingung bei der Eingabe prüfen.
