### ISSUE TITLE
Interface specification

### ISSUE THREAD

**Issue by thb42** [tuiSSE/win-sshfs#6]
We need a specification of the FiSSHBone (Data Model) Interface.
It's nessecssary to communicate with the FiSSHBone and Window developers.
Maybe a separate meeting is appropriate for this issue.

**Comment by thb42** [comment]
It seems to be suitable to organize a meeting with all members to discuss this issue.

**Comment by thb42** [comment]
Momentan habe ich einen Platzhalter für das Interface eingefügt (https://github.com/thb42/win-sshfs/blob/GuiBackend/Sshfs/Sshfs/GuiBackend/IServiceFisshBone.cs)

Dies muss genau definiert werden, außerdem müssen wir noch überlegen ob wir ein Datenmodell 
entwerfen um eindeutig und vollständig Informationen an die GuI zurückzusenden.

Ich würde dafür ein Treffen am Montagabend vorschlagen.

**Comment by bjoe-phi** [comment]
alt!
