### ISSUE TITLE
Daten bei AddServer eintragen

### ISSUE THREAD

**Issue by thb42** [tuiSSE/win-sshfs#62]
Wenn AddServer markiert ist sollten, rechts schon Daten eintragbar sein die per Save Changes übernommen werden und einen neuen Server erzeugen.

**Comment by MSementsov** [comment]
Sollte so funktionieren wie du es dir gewünscht hast, allerdings wirft er mir jetzt eine exception, wenn ich den AddFolder button einfach so doppelklick. Wenn mal jemand das fixen könnte, ich hab jetzt im moment nicht die ursache entdecken können wieso es das macht.

**Comment by MSementsov** [comment]
Bjö-Phi hats gefixt. Ist jetzt voll funktionsfähig.
