### ISSUE TITLE
Drag n Drop bei gemounteten Verzeichnissen

### ISSUE THREAD

**Issue by thb42** [tuiSSE/win-sshfs#67]
Wenn man Drag n Drop mit gemounteten Verzeichnissen verwendet, verschwindet das Verzeichnis.

**Comment by bjoe-phi** [comment]
Kannst du das genauer beschreiben und reproduzieren?
Ich verstehe nicht was du meinst, bei wir verschwindet nichts.

**Comment by thb42** [comment]
Wenn ich mich recht entsinne wurde ein gemountetes Verzeichnis von einem Server per drag and drop zu einem anderen Server verschoben.

**Comment by bjoe-phi** [comment]
Und was ist dabei verschwunden?

**Comment by thb42** [comment]
Na der Verzeichniseintrag in der Liste.

**Comment by bjoe-phi** [comment]
Falls du damit meinst, dass der Eintrag in ein anderen Server verschoben wurde, macht es ja genau das, was es soll ...

**Comment by thb42** [comment]
Wie gesagt, ich bin mir nicht 100%ig was passiert ist, meine Testperson hat vielmehr den Eintrag verschoben und (vermutlich) auf einem anderen Server fallen lassen. Danach konnten wir den Eintrag nicht mehr finden. Es kann natürlich auch sein, dass der Fehler nicht ohne weiteres Reproduziert werden kann.

**Comment by thb42** [comment]
Ich habe es eben noch mal ausprobiert und da ich den Fehler nicht reproduzieren kann schließe ich jetzt das Ticket.
